### ISSUE TITLE
Change some functions names

### ISSUE THREAD

**Issue by eseffar** [SingerLab/gac#30]
Some functions may need a little change in their name to be more relevant when we want to link genomic position and genes, for example something like this :
list_genes  --> list_genes_coordinates / list_genes_chrompos?
find_genes --> find_genes_coordinates /  find_genes_chrompos? 

Thank you

**Comment by RodrigoGM** [comment]
resolved, modified function names to reflect their output in #32 , see https://github.com/SingerLab/gac/blob/51dc90dd21e2af26ebecf2fa3fcd30832da75dc6/R/gene_lookups.R#L28
